# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: backstagedemo9090
#   description: An example of a Backstage application.
#   # Example for optional annotations
#   # annotations:
#   #   github.com/project-slug: backstage/backstage
#   #   backstage.io/techdocs-ref: dir:.
# spec:
#   type: website
#   owner: john@example.com
#   lifecycle: experimental

apiVersion: backstage.io/v1beta3
kind: API
metadata:
  name: my-api
  description: API for managing core banking operations
  tags:
    - banking
spec:
  type: openapi
  lifecycle: production
  owner: core-banking-team
  definition:
    openapi: 3.0.0
    info:
      title: My API
      version: 1.0.0
    paths:
      /accounts:
        get:
          summary: Retrieve all accounts
          responses:
            '200':
              description: A list of accounts
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        balance:
                          type: number
                        owner:
                          type: string
